version: '3.9'
services:
  nest-api:
    container_name: fs-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres
    container_name: localhost
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
